#!/usr/bin/env bash
set -euo pipefail

LAB_MANAGE_SHARED_DIR_WAS_SET="${LAB_MANAGE_SHARED_DIR+x}"
LAB_MANAGE_PRIVATE_DIR_WAS_SET="${LAB_MANAGE_PRIVATE_DIR+x}"
LAB_MANAGE_CONFIG_DIR_WAS_SET="${LAB_MANAGE_CONFIG_DIR+x}"
LAB_MANAGE_SHARED_BASHRC_FILE_WAS_SET="${LAB_MANAGE_SHARED_BASHRC_FILE+x}"
LAB_MANAGE_BASHRC_DEFAULTS_FILE_WAS_SET="${LAB_MANAGE_BASHRC_DEFAULTS_FILE+x}"
CONFIG_FILE="${LAB_MANAGE_CONFIG_FILE:-/etc/default/lab-manage}"
LABGROUP="${LAB_MANAGE_LABGROUP:-labusers}"
TEAMGROUP="${LAB_MANAGE_TEAMGROUP:-labteams}"
DATA_DIR="${LAB_MANAGE_DATA_DIR:-/data}"
SHARED_DIR="${LAB_MANAGE_SHARED_DIR:-${DATA_DIR}/shared}"
PRIVATE_DIR="${LAB_MANAGE_PRIVATE_DIR:-${DATA_DIR}/private}"
CONFIG_DIR="${LAB_MANAGE_CONFIG_DIR:-${DATA_DIR}/config}"
SHARED_BASHRC_FILE="${LAB_MANAGE_SHARED_BASHRC_FILE:-${LAB_MANAGE_BASHRC_DEFAULTS_FILE:-${CONFIG_DIR}/shared_bashrc}}"
INSTALL_PATH="${LAB_MANAGE_INSTALL_PATH:-/usr/local/bin/lab-manage}"
CRON_ENTRY="${LAB_MANAGE_CRON_ENTRY:-*/30 * * * * ${INSTALL_PATH} sync >/dev/null 2>&1}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANAGE_SRC="${SCRIPT_DIR}/lab-manage"

log_info() {
    echo -e "\033[34m[INFO]\033[0m $*"
}

log_warn() {
    echo -e "\033[33m[WARN]\033[0m $*"
}

log_error() {
    echo -e "\033[31m[ERROR]\033[0m $*"
}

log_success() {
    echo -e "\033[32m[OK]\033[0m $*"
}

shell_quote() {
    printf '%q' "$1"
}

if [[ "${LAB_MANAGE_TEST_SKIP_ROOT:-0}" != "1" && $EUID -ne 0 ]]; then
    log_error "Must be run as root"
    exit 1
fi

local_deps=("curl" "useradd" "userdel" "usermod" "passwd" "getent" "crontab" "groupadd" "install" "mountpoint")
for tool in "${local_deps[@]}"; do
    if ! command -v "$tool" &>/dev/null; then
        log_error "Required tool '$tool' not found"
        exit 1
    fi
done

if [[ ! -f "$MANAGE_SRC" ]]; then
    log_error "lab-manage not found next to install.sh"
    exit 1
fi

ensure_group() {
    local group_name="$1"

    if getent group "$group_name" &>/dev/null; then
        log_info "Group '$group_name' already exists"
    else
        groupadd "$group_name"
        log_success "Group '$group_name' created"
    fi
}

ensure_group "$LABGROUP"
ensure_group "$TEAMGROUP"

if ! (mountpoint -q "$DATA_DIR" 2>/dev/null || [[ -d "$DATA_DIR" ]]); then
    log_error "$DATA_DIR directory does not exist. Mount storage first."
    exit 1
fi

config_file_dir="$(dirname "$CONFIG_FILE")"
mkdir -p "$config_file_dir"
{
    echo "# lab-manage runtime configuration."
    echo "# Generated by install.sh. Edit this file or rerun install.sh with LAB_MANAGE_* overrides."
    printf 'LAB_MANAGE_LABGROUP=%s\n' "$(shell_quote "$LABGROUP")"
    printf 'LAB_MANAGE_TEAMGROUP=%s\n' "$(shell_quote "$TEAMGROUP")"
    printf 'LAB_MANAGE_DATA_DIR=%s\n' "$(shell_quote "$DATA_DIR")"
    if [[ -n "$LAB_MANAGE_SHARED_DIR_WAS_SET" ]]; then
        printf 'LAB_MANAGE_SHARED_DIR=%s\n' "$(shell_quote "$SHARED_DIR")"
    fi
    if [[ -n "$LAB_MANAGE_PRIVATE_DIR_WAS_SET" ]]; then
        printf 'LAB_MANAGE_PRIVATE_DIR=%s\n' "$(shell_quote "$PRIVATE_DIR")"
    fi
    if [[ -n "$LAB_MANAGE_CONFIG_DIR_WAS_SET" ]]; then
        printf 'LAB_MANAGE_CONFIG_DIR=%s\n' "$(shell_quote "$CONFIG_DIR")"
    fi
    if [[ -n "$LAB_MANAGE_SHARED_BASHRC_FILE_WAS_SET" || -n "$LAB_MANAGE_BASHRC_DEFAULTS_FILE_WAS_SET" ]]; then
        printf 'LAB_MANAGE_SHARED_BASHRC_FILE=%s\n' "$(shell_quote "$SHARED_BASHRC_FILE")"
    fi
} > "$CONFIG_FILE"
chown root:root "$CONFIG_FILE" 2>/dev/null || true
chmod 644 "$CONFIG_FILE"
log_success "Wrote runtime config to $CONFIG_FILE"

mkdir -p "$SHARED_DIR"
chown root:root "$SHARED_DIR" 2>/dev/null || true
chmod 777 "$SHARED_DIR"
log_success "$SHARED_DIR is ready (mode 777, accessible to all users)"

mkdir -p "$PRIVATE_DIR"
chmod 755 "$PRIVATE_DIR"
log_success "$PRIVATE_DIR is ready (mode 755)"

mkdir -p "$CONFIG_DIR"
chown root:root "$CONFIG_DIR" 2>/dev/null || true
chmod 755 "$CONFIG_DIR"

shared_bashrc_dir="$(dirname "$SHARED_BASHRC_FILE")"
mkdir -p "$shared_bashrc_dir"
if [[ ! -f "$SHARED_BASHRC_FILE" ]]; then
    cat > "$SHARED_BASHRC_FILE" <<'EOF'
# Lab-wide shell defaults.
# Add shared environment variables, aliases, or shell setup here.
EOF
fi
chown root:root "$SHARED_BASHRC_FILE" 2>/dev/null || true
chmod 644 "$SHARED_BASHRC_FILE"
log_success "$SHARED_BASHRC_FILE is ready (read-only for lab users)"

install -m 755 "$MANAGE_SRC" "$INSTALL_PATH"
log_success "Installed lab-manage to $INSTALL_PATH"

existing_cron="$(crontab -l 2>/dev/null || true)"
if printf '%s\n' "$existing_cron" | grep -Fq "$INSTALL_PATH sync"; then
    log_info "Cron job already registered"
else
    {
        [[ -n "$existing_cron" ]] && printf '%s\n' "$existing_cron"
        printf '%s\n' "$CRON_ENTRY"
    } | crontab -
    log_success "Cron job registered (every 30 minutes)"
fi

log_info "Installation complete!"
log_info "  - ${LABGROUP} group: ready"
log_info "  - ${TEAMGROUP} group: ready"
log_info "  - ${SHARED_DIR}: ready (mode 2777)"
log_info "  - ${PRIVATE_DIR}: ready (mode 755)"
log_info "  - ${CONFIG_FILE}: ready (mode 644)"
log_info "  - ${SHARED_BASHRC_FILE}: ready (mode 644)"
log_info "  - lab-manage: installed to $(dirname "$INSTALL_PATH")/"
log_info "  - Cron: SSH key sync every 30 minutes"
log_info ""
log_info "Get started: lab-manage add <github-username>"
